language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
install:
  - "pip3 install pep8"
  - "pip3 install nose"
  - "pip3 install docopt"
  - "pip3 install netaddr"
  - "apt-get install python3-ipaddr"
script:
  ./tests.sh
